import React, { useState } from 'react';
import { Itinerary, TransportMode } from '../types';
import { Calendar, MapPin, ChevronDown, ChevronUp, CreditCard, CheckCircle, ShieldAlert, Youtube, Share2, Lock, Eye, EyeOff, Car, Hotel, Map as MapIcon, ExternalLink, Save, Copy } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface ItineraryDisplayProps {
  data: Itinerary;
  onSave: () => void;
  isSaved?: boolean;
}

const ItineraryDisplay: React.FC<ItineraryDisplayProps> = ({ data, onSave, isSaved = false }) => {
  const [expandedDay, setExpandedDay] = useState<number | null>(1);
  const [revealedTips, setRevealedTips] = useState<boolean>(false);

  const toggleDay = (dayNum: number) => {
    setExpandedDay(expandedDay === dayNum ? null : dayNum);
  };

  const openMapsRoute = () => {
     // Determine Google Maps travel mode based on transport mode
     let travelModeParam = 'driving';
     switch (data.transportMode) {
         case TransportMode.WALK:
             travelModeParam = 'walking';
             break;
         case TransportMode.BUS:
         case TransportMode.TRAIN:
             travelModeParam = 'transit';
             break;
         case TransportMode.CAR:
             travelModeParam = 'driving';
             break;
         case TransportMode.FLIGHT:
             // Google Maps directions usually default to driving/transit for flight legs unless specifically 'flying' which isn't a standard dir param
             // We'll default to driving as a fallback or let user choose
             travelModeParam = 'driving'; 
             break;
         default:
             travelModeParam = 'driving';
     }

     const url = `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent("Current Location")}&destination=${encodeURIComponent(data.destinationName)}&travelmode=${travelModeParam}`;
     window.open(url, '_blank');
  };

  const openHotelSearch = () => {
      const url = `https://www.google.com/maps/search/hotels+in+${encodeURIComponent(data.bookingSuggestions.hotelArea)}+${encodeURIComponent(data.destinationName)}`;
      window.open(url, '_blank');
  };

  const openTransportSearch = () => {
      const url = `https://www.google.com/search?q=${encodeURIComponent(data.bookingSuggestions.transportType + " rental in " + data.destinationName)}`;
      window.open(url, '_blank');
  };

  const handleShare = async () => {
    const shareText = `✈️ Trip to ${data.destinationName} with PlanMesh!\n\n${data.overview}\n\n💰 Est. Cost: ${data.totalEstimatedCost}\n📅 Duration: ${data.durationDays} Days\n\nGenerated by PlanMesh.`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Trip to ${data.destinationName}`,
          text: shareText,
          url: window.location.href,
        });
      } catch (error) {
        console.error('Error sharing:', error);
      }
    } else {
      try {
        await navigator.clipboard.writeText(shareText);
        alert('Itinerary details copied to clipboard!');
      } catch (err) {
        console.error('Failed to copy:', err);
      }
    }
  };

  return (
    <div className="space-y-8 text-white">
      {/* Header Info Card */}
      <div className="glass-panel p-1 rounded-[2.5rem] relative overflow-hidden">
        <div className="bg-dark-900/80 rounded-[2.2rem] p-8 relative z-10">
            <div className="flex flex-col gap-6">
                <div className="flex justify-between items-start">
                    <div>
                        <span className="text-neon-lime font-mono text-xs font-bold uppercase tracking-widest mb-2 block">Destination Unlocked</span>
                        <h2 className="text-5xl md:text-6xl font-grotesk font-black uppercase leading-none text-white mb-4">
                            {data.destinationName}
                        </h2>
                    </div>
                    <div className="flex gap-2">
                        <button 
                            onClick={onSave}
                            className={`p-3 rounded-full transition-all group border border-white/20 ${isSaved ? 'bg-neon-lime text-black hover:bg-neon-lime cursor-default' : 'bg-white/10 hover:bg-neon-lime hover:text-black'}`}
                            title="Save Trip for Later"
                            disabled={isSaved}
                        >
                            {isSaved ? <CheckCircle className="w-6 h-6" /> : <Save className="w-6 h-6" />}
                        </button>
                        <button 
                            onClick={openMapsRoute}
                            className="bg-white/10 p-3 rounded-full hover:bg-neon-cyan hover:text-black transition-all group border border-white/20"
                            title="Navigate on Google Maps"
                        >
                            <MapIcon className="w-6 h-6" />
                        </button>
                        <button 
                            onClick={handleShare}
                            className="bg-white/10 p-3 rounded-full hover:bg-white/20 cursor-pointer transition-colors border border-white/20"
                            title="Share Itinerary"
                        >
                            <Share2 className="w-6 h-6 text-white" />
                        </button>
                    </div>
                </div>
                
                <p className="text-gray-300 text-lg font-medium leading-relaxed border-l-2 border-white/20 pl-4">{data.overview}</p>
                
                <div className="flex flex-wrap gap-3 pt-4">
                    <div className="flex items-center gap-2 bg-white text-black px-4 py-2 rounded-full font-bold font-grotesk text-sm">
                        <CreditCard className="w-4 h-4" />
                        <span>{data.totalEstimatedCost}</span>
                    </div>
                    <div className="flex items-center gap-2 bg-black border border-white/20 px-4 py-2 rounded-full font-bold font-grotesk text-sm text-gray-300">
                        <Calendar className="w-4 h-4" />
                        <span>{data.durationDays} Days</span>
                    </div>
                </div>
            </div>
        </div>
        
        {/* Decorative background elements */}
        <div className="absolute -top-20 -right-20 w-80 h-80 bg-neon-lime/20 rounded-full blur-[80px] pointer-events-none"></div>
        <div className="absolute -bottom-20 -left-20 w-80 h-80 bg-neon-purple/20 rounded-full blur-[80px] pointer-events-none"></div>
      </div>

      {/* Concierge / Booking Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
           <button 
             onClick={openHotelSearch}
             className="flex flex-col p-5 rounded-2xl bg-gradient-to-br from-gray-900 to-black border border-white/10 hover:border-neon-purple/50 transition-all group text-left relative overflow-hidden"
           >
              <div className="absolute top-0 right-0 w-24 h-24 bg-neon-purple/10 rounded-full blur-[30px] group-hover:bg-neon-purple/20 transition-all"></div>
              <div className="flex items-center gap-3 mb-2 relative z-10">
                 <Hotel className="w-5 h-5 text-neon-purple" />
                 <span className="text-xs font-bold uppercase tracking-widest text-gray-500">Stay Recommendation</span>
              </div>
              <div className="font-grotesk font-bold text-lg text-white relative z-10">
                  Area: {data.bookingSuggestions.hotelArea}
              </div>
              <div className="mt-2 text-xs text-neon-purple flex items-center gap-1">
                 Check prices on Maps <ExternalLink className="w-3 h-3" />
              </div>
           </button>

           <button 
             onClick={openTransportSearch}
             className="flex flex-col p-5 rounded-2xl bg-gradient-to-br from-gray-900 to-black border border-white/10 hover:border-neon-cyan/50 transition-all group text-left relative overflow-hidden"
           >
              <div className="absolute top-0 right-0 w-24 h-24 bg-neon-cyan/10 rounded-full blur-[30px] group-hover:bg-neon-cyan/20 transition-all"></div>
              <div className="flex items-center gap-3 mb-2 relative z-10">
                 <Car className="w-5 h-5 text-neon-cyan" />
                 <span className="text-xs font-bold uppercase tracking-widest text-gray-500">Ride Recommendation</span>
              </div>
              <div className="font-grotesk font-bold text-lg text-white relative z-10">
                  {data.bookingSuggestions.transportType}
              </div>
              <div className="mt-2 text-xs text-neon-cyan flex items-center gap-1">
                 Find rentals <ExternalLink className="w-3 h-3" />
              </div>
           </button>
      </div>

      {/* Secret Tips Section */}
      <div className="bg-black border border-white/10 rounded-3xl p-1 relative overflow-hidden group">
         <div className="absolute inset-0 bg-stripes-gray opacity-10"></div>
         <div className="bg-dark-950/90 p-6 rounded-[1.3rem] relative z-10">
             <div className="flex items-center justify-between mb-4">
                 <div className="flex items-center gap-3">
                     <div className="bg-red-500/20 p-2 rounded-lg border border-red-500/30">
                        <Lock className="w-4 h-4 text-red-500" />
                     </div>
                     <h3 className="font-grotesk font-black uppercase text-xl tracking-tight">Top Secret Intel</h3>
                 </div>
                 <button 
                    onClick={() => setRevealedTips(!revealedTips)}
                    className="text-xs font-bold uppercase flex items-center gap-2 bg-white/5 px-3 py-1.5 rounded-lg hover:bg-white/10 transition-colors"
                 >
                     {revealedTips ? <><EyeOff className="w-3 h-3" /> Re-encrypt</> : <><Eye className="w-3 h-3" /> Reveal</>}
                 </button>
             </div>

             <div className="space-y-3">
                 {data.secretTips.map((tip, idx) => (
                     <div key={idx} className="relative">
                         <div className={`p-4 rounded-xl bg-white/5 border border-white/5 transition-all duration-500 ${revealedTips ? 'filter-none' : 'blur-sm select-none'}`}>
                             <p className="font-medium text-sm text-gray-300 leading-relaxed">
                                <span className="text-red-500 mr-2 font-bold">CONFIDENTIAL:</span> 
                                {tip}
                             </p>
                         </div>
                         {!revealedTips && (
                             <div className="absolute inset-0 flex items-center justify-center cursor-pointer z-20" onClick={() => setRevealedTips(true)}>
                                 <span className="bg-black/80 text-white text-[10px] font-bold uppercase px-3 py-1 rounded border border-white/20 backdrop-blur-md">
                                     Tap to Decrypt
                                 </span>
                             </div>
                         )}
                     </div>
                 ))}
             </div>
         </div>
      </div>

      {/* Essentials Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {/* Safety & Info */}
          <div className="bg-dark-900/60 backdrop-blur-md rounded-3xl border border-white/10 p-6 flex flex-col gap-4 group hover:border-orange-500/50 transition-all duration-300">
              <div className="flex items-center justify-between">
                  <h3 className="text-xl font-grotesk font-bold uppercase text-gray-400 group-hover:text-orange-400 transition-colors">The Intel</h3>
                  <ShieldAlert className="w-6 h-6 text-gray-600 group-hover:text-orange-500 transition-colors" />
              </div>
              
              <div className="bg-black/40 p-4 rounded-2xl border border-white/5">
                 <div className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Currency Exchange</div>
                 <div className="font-mono text-xl text-white">{data.exchangeRateInfo}</div>
              </div>

              <div className="space-y-3 mt-2">
                  {data.precautions.map((item, idx) => (
                      <div key={idx} className="flex items-start gap-3 text-sm text-gray-300 bg-white/5 p-3 rounded-xl">
                          <span className="text-orange-500 mt-0.5 text-xs">⚠️</span> 
                          <span className="font-medium">{item}</span>
                      </div>
                  ))}
              </div>
          </div>

          {/* Content / Vibes */}
          <div className="bg-dark-900/60 backdrop-blur-md rounded-3xl border border-white/10 p-6 flex flex-col gap-4 group hover:border-red-500/50 transition-all duration-300">
              <div className="flex items-center justify-between">
                  <h3 className="text-xl font-grotesk font-bold uppercase text-gray-400 group-hover:text-red-400 transition-colors">Pre-Trip Watchlist</h3>
                  <Youtube className="w-6 h-6 text-gray-600 group-hover:text-red-500 transition-colors" />
              </div>
              
              <div className="space-y-2">
                  {data.youtubeSearchTerms.map((term, idx) => (
                      <a 
                        key={idx}
                        href={`https://www.youtube.com/results?search_query=${encodeURIComponent(term)}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center justify-between p-4 bg-black/20 hover:bg-red-600 hover:text-white border border-white/5 rounded-xl transition-all group/link"
                      >
                          <span className="text-sm font-bold font-grotesk truncate pr-4">{term}</span>
                          <ArrowRight className="w-4 h-4 opacity-0 group-hover/link:opacity-100 -translate-x-2 group-hover/link:translate-x-0 transition-all" />
                      </a>
                  ))}
              </div>
          </div>
      </div>

      {/* Days Feed */}
      <div className="space-y-6 relative">
        <div className="absolute left-6 top-0 bottom-0 w-px bg-gradient-to-b from-brand-500 via-white/10 to-transparent z-0 md:left-8"></div>
        
        <h3 className="text-3xl font-grotesk font-black uppercase flex items-center gap-3 relative z-10 pl-4">
           Itinerary
        </h3>

        {data.days.map((day) => (
          <div key={day.dayNumber} className="relative z-10 pl-4 md:pl-6">
            <div className="bg-dark-900 border border-white/10 rounded-3xl overflow-hidden hover:border-white/30 transition-all duration-300 shadow-xl">
                
                {/* Day Header */}
                <button
                onClick={() => toggleDay(day.dayNumber)}
                className="w-full p-6 flex items-center justify-between bg-gradient-to-r from-white/5 to-transparent"
                >
                    <div className="flex items-center gap-5">
                        <div className={`w-14 h-14 rounded-2xl flex items-center justify-center font-black font-grotesk text-2xl border-2 ${
                            expandedDay === day.dayNumber 
                            ? 'bg-white text-black border-white rotate-3 scale-110 shadow-lg shadow-white/20' 
                            : 'bg-black text-gray-500 border-white/10'
                        } transition-all duration-300`}>
                            {day.dayNumber}
                        </div>
                        <div className="text-left">
                            <div className="text-xs font-bold text-neon-purple uppercase tracking-wider mb-1">Day {day.dayNumber}</div>
                            <h4 className="font-bold text-xl md:text-2xl text-white font-grotesk uppercase">{day.theme}</h4>
                        </div>
                    </div>
                    <div className={`w-10 h-10 rounded-full border border-white/10 flex items-center justify-center transition-transform duration-300 ${expandedDay === day.dayNumber ? 'bg-white text-black rotate-180' : 'bg-black text-white'}`}>
                        <ChevronDown className="w-5 h-5" />
                    </div>
                </button>

                <AnimatePresence>
                {expandedDay === day.dayNumber && (
                    <motion.div
                    initial={{ height: 0, opacity: 0, scale: 0.95 }}
                    animate={{ height: "auto", opacity: 1, scale: 1 }}
                    exit={{ height: 0, opacity: 0, scale: 0.95 }}
                    transition={{ duration: 0.3, ease: "easeOut" }}
                    >
                    <div className="p-6 pt-2 border-t border-white/5 space-y-4">
                        
                        {/* Daily Quote */}
                        <div className="bg-neon-lime/10 border border-neon-lime/20 p-4 rounded-xl text-center relative overflow-hidden">
                             <div className="absolute -top-2 -left-2 text-4xl text-neon-lime opacity-20 font-serif">"</div>
                             <p className="font-grotesk font-bold text-neon-lime text-sm md:text-base italic">
                                {day.dailyQuote}
                             </p>
                             <div className="absolute -bottom-4 -right-2 text-4xl text-neon-lime opacity-20 font-serif">"</div>
                        </div>

                        <div className="text-gray-400 mb-6 font-sans font-medium px-2 border-l-2 border-white/20 pl-4">{day.summary}</div>
                        
                        {day.activities.map((activity, idx) => (
                        <div key={idx} className="bg-black/40 rounded-2xl p-5 border border-white/5 hover:bg-white/5 transition-colors relative overflow-hidden group">
                            <div className="flex flex-col gap-3 relative z-10">
                                <div className="flex justify-between items-start">
                                    <h5 className="text-white font-bold text-lg font-grotesk leading-tight">{activity.title}</h5>
                                    <span className="text-[10px] font-black font-mono bg-brand-500 text-white px-2 py-1 rounded self-start">
                                        {activity.time}
                                    </span>
                                </div>
                                <p className="text-gray-400 text-sm font-medium">{activity.description}</p>
                                
                                <div className="flex flex-wrap gap-3 mt-2 pt-3 border-t border-white/5">
                                    {activity.location && (
                                        <button 
                                            onClick={(e) => {
                                                e.stopPropagation();
                                                window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(activity.title + " " + activity.location)}`, '_blank');
                                            }}
                                            className="flex items-center gap-1.5 text-xs font-bold text-gray-300 hover:text-neon-cyan uppercase tracking-wide transition-colors"
                                        >
                                            <MapPin className="w-3 h-3" /> {activity.location}
                                        </button>
                                    )}
                                    {activity.estimatedCost && (
                                        <span className="flex items-center gap-1.5 text-xs font-bold text-gray-300 uppercase tracking-wide">
                                        <DollarSign className="w-3 h-3 text-neon-lime" /> {activity.estimatedCost}
                                        </span>
                                    )}
                                </div>
                            </div>
                            {/* Hover Glow */}
                            <div className="absolute -right-10 -bottom-10 w-32 h-32 bg-white/5 rounded-full blur-[40px] group-hover:bg-white/10 transition-all"></div>
                        </div>
                        ))}
                    </div>
                    </motion.div>
                )}
                </AnimatePresence>
            </div>
          </div>
        ))}
      </div>

      {/* Packing Checklist */}
      <div className="bg-gradient-to-br from-brand-900/20 to-black p-1 rounded-[2.5rem] mt-12">
        <div className="bg-dark-950/90 backdrop-blur-xl rounded-[2.3rem] p-8 border border-brand-500/20">
            <h3 className="text-2xl font-grotesk font-black uppercase mb-6 flex items-center gap-3 text-white">
            <CheckCircle className="w-8 h-8 text-neon-lime" /> Bag Check
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {data.packingTips.map((tip, i) => (
                    <div key={i} className="flex items-center gap-4 text-gray-300 text-sm bg-white/5 p-4 rounded-2xl border border-white/5 hover:bg-white/10 transition-colors cursor-default">
                        <div className="w-5 h-5 rounded-full border-2 border-gray-600 flex items-center justify-center flex-shrink-0"></div>
                        <span className="font-medium">{tip}</span>
                    </div>
                ))}
            </div>
        </div>
      </div>
    </div>
  );
};

// Helper icon
const DollarSign: React.FC<{className?: string}> = ({className}) => (
  <svg className={className} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="1" x2="12" y2="23"></line><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>
);

const ArrowRight: React.FC<{className?: string}> = ({className}) => (
    <svg className={className} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>
);

export default ItineraryDisplay;